<template>
  <div class="space-y-8">
    <!-- Header -->
    <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
      <div>
        <h1 class="text-3xl font-bold text-slate-900 mb-2">Match Management</h1>
        <p class="text-slate-600">View and manage your club's matches across tournaments</p>
      </div>
      <div class="px-4 py-2 rounded-2xl bg-gradient-to-r from-blue-50 to-indigo-50 border border-blue-200">
        <span class="text-sm font-semibold text-blue-700">{{ matches.length }} Total Matches</span>
      </div>
    </div>

    <!-- Tournament Filter -->
    <div class="bg-white rounded-3xl shadow-xl shadow-slate-500/10 border border-slate-100/50 p-6">
      <div class="flex flex-col sm:flex-row sm:items-center gap-4">
        <div class="flex items-center gap-3">
          <div class="w-10 h-10 rounded-2xl bg-gradient-to-br from-purple-500 to-pink-600 flex items-center justify-center">
            <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2.586a1 1 0 01-.293.707l-6.414 6.414a1 1 0 00-.293.707V17l-4 4v-6.586a1 1 0 00-.293-.707L3.293 7.293A1 1 0 013 6.586V4z"/>
            </svg>
          </div>
          <label class="text-sm font-semibold text-slate-900">Filter by Tournament:</label>
        </div>
        <select v-model="selectedTournament" @change="loadMatches" 
                class="px-4 py-3 border-2 border-slate-200 rounded-2xl text-sm font-medium focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-white">
          <option value="">All Tournaments</option>
          <option v-for="tournament in tournaments" :key="tournament._id" :value="tournament._id">
            {{ tournament.name }}
          </option>
        </select>
      </div>
    </div>

    <!-- Match Status Tabs -->
    <div class="bg-white rounded-3xl shadow-xl shadow-slate-500/10 border border-slate-100/50 overflow-hidden">
      <div class="border-b border-slate-200/50 bg-gradient-to-r from-slate-50 to-blue-50/30">
        <nav class="flex">
          <button v-for="tab in tabs" :key="tab.key" @click="activeTab = tab.key"
                  :class="[
                    'relative px-8 py-5 text-sm font-semibold transition-all duration-300',
                    activeTab === tab.key 
                      ? 'text-blue-600 bg-white shadow-lg' 
                      : 'text-slate-600 hover:text-slate-900 hover:bg-white/50'
                  ]">
            <span class="relative z-10">{{ tab.label }}</span>
            <span v-if="tab.count !== undefined" class="ml-3 px-2.5 py-1 rounded-full text-xs font-bold bg-gradient-to-r from-blue-500 to-indigo-600 text-white shadow-lg">
              {{ tab.count }}
            </span>
            <div v-if="activeTab === tab.key" class="absolute inset-x-0 bottom-0 h-1 bg-gradient-to-r from-blue-500 to-indigo-600 rounded-t-full"></div>
          </button>
        </nav>
      </div>

      <div class="p-8">
        <!-- Loading State -->
        <div v-if="loading" class="text-center py-16">
          <div class="inline-block animate-spin rounded-full h-12 w-12 border-4 border-blue-500 border-t-transparent"></div>
          <p class="text-slate-600 mt-4 font-medium">Loading matches...</p>
        </div>

        <!-- Empty State -->
        <div v-else-if="filteredMatches.length === 0" class="text-center py-20">
          <div class="w-24 h-24 mx-auto mb-6 rounded-3xl bg-gradient-to-br from-slate-100 to-slate-200 flex items-center justify-center">
            <svg class="w-12 h-12 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"/>
            </svg>
          </div>
          <h3 class="text-xl font-bold text-slate-900 mb-3">No {{ activeTab }} Matches</h3>
          <p class="text-slate-600 max-w-md mx-auto">
            <span v-if="activeTab === 'upcoming'">No upcoming matches scheduled. Matches will appear here once fixtures are generated for tournaments your club is participating in.</span>
            <span v-else-if="activeTab === 'ongoing'">No matches currently in progress.</span>
            <span v-else>No completed matches to display.</span>
          </p>
          <div v-if="activeTab === 'upcoming'" class="mt-4 text-sm text-slate-500">
            <p>Make sure your club is registered for tournaments and fixtures have been generated by the tournament organizers.</p>
          </div>
        </div>

        <!-- Matches Grid -->
        <div v-else class="grid gap-6">
          <div v-for="match in filteredMatches" :key="match._id" 
               :class="[
                 'group bg-white border-2 rounded-3xl p-8 transition-all duration-300',
                 match.status === 'upcoming' ? 'border-blue-100 hover:border-blue-200 hover:shadow-2xl hover:shadow-blue-500/10' :
                 match.status === 'ongoing' ? 'border-orange-100 hover:border-orange-200 hover:shadow-2xl hover:shadow-orange-500/10' :
                 'border-green-100 hover:border-green-200 hover:shadow-2xl hover:shadow-green-500/10'
               ]">
            <div class="flex flex-col lg:flex-row lg:items-center gap-6">
              <!-- Match Info -->
              <div class="flex-1">
                <div class="flex items-center gap-3 mb-4">
                  <span :class="[
                    'px-4 py-2 rounded-2xl text-sm font-bold',
                    match.status === 'upcoming' ? 'bg-blue-100 text-blue-700' :
                    match.status === 'ongoing' ? 'bg-orange-100 text-orange-700' :
                    'bg-green-100 text-green-700'
                  ]">
                    {{ match.status?.charAt(0).toUpperCase() + match.status?.slice(1) }}
                  </span>
                  <span class="text-sm text-slate-600 font-medium">{{ match.tournament?.name }}</span>
                  <span v-if="match.round || match.stage" class="px-3 py-1 bg-slate-100 text-slate-700 rounded-full text-xs font-medium">
                    {{ match.round || match.stage }}
                  </span>
                </div>
                
                <div class="flex items-center justify-center gap-8 mb-6">
                  <!-- Your Club -->
                  <div class="text-center flex-1">
                    <div class="w-16 h-16 rounded-3xl bg-gradient-to-br from-blue-500 to-indigo-600 flex items-center justify-center text-white text-xl font-bold mx-auto mb-3 shadow-lg">
                      <img v-if="match.team1?.logoUrl" :src="match.team1.logoUrl" class="w-full h-full rounded-3xl object-cover" @error="$event.target.style.display='none'" />
                      <span v-else>{{ match.team1?.name?.charAt(0)?.toUpperCase() || 'C' }}</span>
                    </div>
                    <h3 class="font-bold text-slate-900 text-lg">{{ match.team1?.name || 'Your Club' }}</h3>
                    <p class="text-sm text-blue-600 font-medium">Your Team</p>
                  </div>
                  
                  <!-- VS -->
                  <div class="text-center">
                    <div class="w-12 h-12 rounded-2xl bg-gradient-to-br from-slate-200 to-slate-300 flex items-center justify-center text-slate-600 font-bold text-lg shadow-lg">
                      VS
                    </div>
                  </div>
                  
                  <!-- Opponent -->
                  <div class="text-center flex-1">
                    <div class="w-16 h-16 rounded-3xl bg-gradient-to-br from-purple-500 to-pink-600 flex items-center justify-center text-white text-xl font-bold mx-auto mb-3 shadow-lg">
                      <img v-if="match.team2?.logoUrl" :src="match.team2.logoUrl" class="w-full h-full rounded-3xl object-cover" @error="$event.target.style.display='none'" />
                      <span v-else>{{ match.team2?.name?.charAt(0)?.toUpperCase() || 'O' }}</span>
                    </div>
                    <h3 class="font-bold text-slate-900 text-lg">{{ match.team2?.name || 'Opponent' }}</h3>
                    <p class="text-sm text-purple-600 font-medium">Opponent</p>
                  </div>
                </div>

                <!-- Match Details -->
                <div class="grid sm:grid-cols-3 gap-4">
                  <div class="flex items-center gap-3">
                    <div class="w-8 h-8 rounded-xl bg-blue-100 flex items-center justify-center">
                      <svg class="w-4 h-4 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"/>
                      </svg>
                    </div>
                    <div>
                      <p class="text-xs text-slate-500 font-medium">Date</p>
                      <p class="text-sm font-semibold text-slate-900">{{ formatDate(match.date) }}</p>
                    </div>
                  </div>
                  
                  <div class="flex items-center gap-3">
                    <div class="w-8 h-8 rounded-xl bg-green-100 flex items-center justify-center">
                      <svg class="w-4 h-4 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"/>
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"/>
                      </svg>
                    </div>
                    <div>
                      <p class="text-xs text-slate-500 font-medium">Venue</p>
                      <p class="text-sm font-semibold text-slate-900">{{ match.venue || 'TBD' }}</p>
                    </div>
                  </div>
                  
                  <div class="flex items-center gap-3">
                    <div class="w-8 h-8 rounded-xl bg-purple-100 flex items-center justify-center">
                      <svg class="w-4 h-4 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"/>
                      </svg>
                    </div>
                    <div>
                      <p class="text-xs text-slate-500 font-medium">Time</p>
                      <p class="text-sm font-semibold text-slate-900">{{ formatTime(match.time) }}</p>
                    </div>
                  </div>
                </div>
              </div>

              <!-- Actions -->
              <div class="flex flex-col gap-3 lg:w-48">
                <button @click="viewMatchDetails(match)" 
                        class="px-6 py-3 rounded-2xl bg-gradient-to-r from-blue-500 to-indigo-600 text-white font-semibold hover:from-blue-600 hover:to-indigo-700 transition-all duration-200 shadow-lg hover:shadow-xl">
                  View Match Details
                </button>
                <button v-if="match.status === 'completed'" 
                        @click="viewMatchDetails(match)"
                        class="px-6 py-3 rounded-2xl bg-green-100 hover:bg-green-200 text-green-700 font-semibold transition-colors">
                  View Scorecard
                </button>
              </div>
            </div>

            <!-- Score Display for Completed Matches -->
            <div v-if="match.status === 'completed' && match.score" class="mt-6 pt-6 border-t border-slate-200">
              <div class="bg-gradient-to-r from-green-50 to-emerald-50 rounded-2xl p-4">
                <div class="flex items-center justify-between">
                  <div class="text-center">
                    <p class="text-sm font-medium text-slate-600">{{ match.team1?.name }}</p>
                    <p class="text-2xl font-bold text-slate-900">{{ match.score?.team1 || '0' }}</p>
                  </div>
                  <div class="text-center">
                    <p class="text-sm font-medium text-green-600">Final Score</p>
                    <p class="text-lg font-bold text-green-700">{{ match.result || 'Match Completed' }}</p>
                  </div>
                  <div class="text-center">
                    <p class="text-sm font-medium text-slate-600">{{ match.team2?.name }}</p>
                    <p class="text-2xl font-bold text-slate-900">{{ match.score?.team2 || '0' }}</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
</template>

<script setup>
import { ref, onMounted, computed } from 'vue';
import { useRouter } from 'vue-router';
import axios from 'axios';

const router = useRouter();

const activeTab = ref('upcoming');
const selectedTournament = ref('');
const matches = ref([]);
const tournaments = ref([]);
const loading = ref(false);

const API = import.meta.env.VITE_API_BASE || 'http://localhost:4000/api';

const tabs = computed(() => [
  { key: 'upcoming', label: 'Upcoming', count: matches.value.filter(m => m.status === 'upcoming').length },
  { key: 'ongoing', label: 'Ongoing', count: matches.value.filter(m => m.status === 'ongoing').length },
  { key: 'completed', label: 'Completed', count: matches.value.filter(m => m.status === 'completed').length }
]);

const filteredMatches = computed(() => {
  let filtered = matches.value.filter(match => match.status === activeTab.value);
  if (selectedTournament.value) {
    filtered = filtered.filter(match => match.tournament?._id === selectedTournament.value);
  }
  return filtered;
});

onMounted(async () => {
  await Promise.all([loadMatches(), loadTournaments()]);
});

async function loadMatches() {
  loading.value = true;
  try {
    const response = await axios.get(`${API}/clubs/matches`);
    const raw = response.data.matches || [];
    
    // Transform matches for display
    const norm = raw.map(m => {
      const when = m.date ? new Date(m.date) : null;
      const now = new Date();
      let status = (m.status || '').toString();
      
      // Determine status based on date if not explicitly set
      if (!status) {
        if (when && when > now) status = 'upcoming';
        else status = 'completed';
      }
      
      // Normalize status from backend values (Scheduled/Live/Completed)
      const s = status.toLowerCase();
      const normStatus = s === 'scheduled' ? 'upcoming' : (s === 'live' ? 'ongoing' : (s === 'completed' ? 'completed' : s));
      
      return {
        _id: m._id,
        status: normStatus,
        date: m.date,
        time: m.time,
        venue: m.venue,
        round: m.round,
        stage: m.stage,
        tournament: {
          _id: m.tournament._id,
          name: m.tournament.name,
          status: m.tournament.status,
          format: m.tournament.format
        },
        // Show opponent as team2, current club as team1
        team1: { 
          id: m.isHomeTeam ? m.homeClub._id : m.awayClub._id, 
          name: m.isHomeTeam ? m.homeClub.name : m.awayClub.name,
          logoUrl: m.isHomeTeam ? m.homeClub.logoUrl : m.awayClub.logoUrl
        },
        team2: { 
          id: m.opponent._id, 
          name: m.opponent.name,
          logoUrl: m.opponent.logoUrl
        },
        isHomeTeam: m.isHomeTeam,
        score: m.score || null,
        result: m.result || ''
      };
    });
    
    matches.value = norm;
  } catch (error) {
    console.error('Failed to load matches:', error);
    // Show user-friendly error message
    matches.value = [];
  } finally {
    loading.value = false;
  }
}

async function loadTournaments() {
  try {
    const response = await axios.get(`${API}/tournaments/my-tournaments`);
    tournaments.value = response.data.tournaments || [];
  } catch (error) {
    console.error('Failed to load tournaments:', error);
  }
}

function formatDate(dateString) {
  return new Date(dateString).toLocaleDateString('en-IN', {
    year: 'numeric',
    month: 'short',
    day: 'numeric'
  });
}

function formatTime(timeString) {
  if (!timeString) return 'TBD';
  return new Date(`1970-01-01T${timeString}`).toLocaleTimeString('en-IN', {
    hour: '2-digit',
    minute: '2-digit',
    hour12: true
  });
}

function viewMatchDetails(match) {
  // Navigate to the new match details page
  router.push({ 
    name: 'match-details', 
    params: { 
      id: match.tournament._id, 
      matchId: match._id 
    } 
  });
}
</script>

<style scoped>
/* Custom animations */
@keyframes fadeInUp {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.space-y-8 > * {
  animation: fadeInUp 0.6s ease-out;
}

.space-y-8 > *:nth-child(2) {
  animation-delay: 0.1s;
}

.space-y-8 > *:nth-child(3) {
  animation-delay: 0.2s;
}
</style>